version: '3.8'

services:
  webapi:
    #image: your-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44348:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - app-data:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection1: "Server=db;Database=TestDb;User=sa;Password=r00t.R00T"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #container_name: sql_server_container
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   environment:
  #     - xpack.monitoring.enabled=true
  #     - xpack.watcher.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.type=single-node
  #   networks:
  #     - app-network
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.11.3
  #   ports:
  #     - "5601:5601"
  #   environment:  
  #     - ELASTICSEARCH_URL=http://localhost:9200
  #   networks:
  #     - app-network
  #   depends_on:
  #     - elasticsearch
networks:
  app-network:
    driver: bridge
    
volumes:
  app-data:
  sql-data:
  # es-data:
