version: '3.8'

services:
  webapi:
    #image: your-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44348:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - app-data:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection1: "Server=db;Database=TestDb;User=sa;Password=r00t.R00T"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #container_name: sql_server_container
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql
networks:
  app-network:
    driver: bridge
    
volumes:
  app-data:
  sql-data:
